name: Test Action

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     # - name: Setup remote
       # run: |
        #  echo "${{secrets.SSH_PUBLIC_KEY}}" | sudo tee ~/.ssh/authorized_keys
      - name: Test remote
        uses: ./
        with:
          playbook: test.yml
          directory: ~/
          key: ${{secrets.SSH_PRIVATE_KEY}}
         # inventory: |
         #  localhost ansible_connection=local
